// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Fileinfo    string
	Posts       string
	Preferences string
	Reactions   string
}{
	Fileinfo:    "fileinfo",
	Posts:       "posts",
	Preferences: "preferences",
	Reactions:   "reactions",
}
